Add Intel NuC target
Forestscribe/genivi-dev-platform pull request #5
Opened 2017-02-15 14:15 UTC by turbank

Add the intel nuc target as intel_nuc-core-i5
Install all pakages to get FM USB tuner working with genivi demo app

2017-02-15 15:40 UTC, JeremR commented on .bbtravis.yml
> +  - TARGET=intel_nuc-core-i5
intel-corei7-64 ? as this is the machine name and it should work on any intel core based target ? or I am missing something ?

2017-02-15 15:40 UTC, JeremR commented on .bbtravis.yml
> +  - TARGET=intel_nuc-core-i5
Also currently to make CI working (mainly artifactory push) this value must be the same as MACHINE

2017-02-15 15:40 UTC, JeremR commented on gdp-src-build/conf/templates/intel_nuc-core-i5.local.conf
> +IMAGE_INSTALL_append = " mesa-megadriver qtbase rtl-sdr radioservice alsajackout fmradioqtplugin gstreamer1.0-plugins-good"
you should create a packagegroup in your radioservice layer

2017-02-15 15:57 UTC, JeremR commented on gdp-src-build/conf/templates/intel_nuc-core-i5.local.conf
> +IMAGE_INSTALL_append = " mesa-megadriver qtbase rtl-sdr radioservice alsajackout fmradioqtplugin gstreamer1.0-plugins-good"
or maybe you should fix dependencies in your fmradio.bbappend and others in your layer ?

2017-02-15 19:31 UTC, tardyp requested changes
yeah! its building. Now I believe a git rebase with clean history is required

2017-02-16 08:38 UTC, closed without merging

2017-02-16 08:53 UTC, tardyp commented
why did you close?
You can just do your rebase, and force push to you intel_nuc branch

2017-02-16 08:53 UTC, tardyp commented
then you can reopen the PR to have the CI restart